### PR TITLE
Updates for breaking API changes in v0.41

### PR DESCRIPTION
**Pull request by mstoykov**
This is very small change to the code due to breaking changes in the API in v0.41.0

The release is slated for next week, so please wait until then to merge this. I will try to update the k6 version to v0.41 at that point.

### CODE REVIEW

**Comment by mstoykov** [comment]
This is now ready to be reviewed and merged :bow:

**Comment by timterrill** [comment]
I'd be interested in seeing this get merged! I work for ACV Auctions and we are trying to get k6 metrics into Elastic and are currently working with the previous version of k6 (v0.40.0) in order to get the xk6-es extension to build.  It builds, but we aren't able to get it actually to connect to our elastic instance.

Will this fix allow us to build with k6 v0.41 (which might also give us more luck connecting to elastic hopefully)? Thank you!

**Comment by BarthV** [comment]
Hi, sry for the delay I didn't saw this PR in the first place.

**Comment by BarthV** [comment]
v0.0.2 tag is now available

**Comment by timterrill** [comment]
awesome, thank you so much!

**Pull request merged**
